sudo: false
language: go
go:
    - 1.x
    - 1.8.x
    - 1.7.x
    - 1.6.x
    - 1.5.x
    - 1.4.x
    - tip
before_install:
    - make setup

before_script:
    - go fmt ./...
script:
    - make lint
    - make test
    - make coveralls
matrix:
    allow_failures:
        - go: tip
          fast_finish: true
